name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Config repository
        run: |
          git config --global user.email "github-actions@jorgebg.com"
          git config --global user.name "GitHub Actions"

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.5"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Build cheatsheets
        run: |
          pipenv run python3 -m cheatsheeter

      - name: Push cheatsheets
        run: |
          git add ./docs
          git commit -m"Build cheatsheets"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}